server:
  port: 8081

logging:
  file:
    name: process-management.log
    path: .

spring:
  config:
    activate:
      on-profile: local
  application:
    name: process-management-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sij_process_request
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: create drop
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      mode: always

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  rabbitmq:
    #host: localhost
    #port: 5672
    #username: guest
    #password: guest
    host: 10.72.208.91
    port: 31822
    username: user
    password: 1hQ1n6Z5p5WnkKN4


# springdoc api configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api/docs.html
    operations-sorter: method

# Basic Security
access:
  username: sigo
  password: sigo
  swagger: http://localhost:8081/api/swagger-ui/index.html

# link external
api:
  token-auto: eyJ4NXQiOiJOVGczWW1Ka056WmhaRFJpTW1RME1EazNOR00wWldFeU1qQmhNalV3TjJFMU9XRTJNalkzTVRsak1UUmpZV1F6WXpaak1XTXdOV1ZsWXpneU5XRmtPQSIsImtpZCI6Ik5UZzNZbUprTnpaaFpEUmlNbVEwTURrM05HTTBaV0V5TWpCaE1qVXdOMkUxT1dFMk1qWTNNVGxqTVRSallXUXpZelpqTVdNd05XVmxZemd5TldGa09BX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJwb2xpY2lhbmFjaW9uYWxAcG4uZ292LmN2IiwiYXV0IjoiQVBQTElDQVRJT04iLCJhdWQiOiJiU0dmUVFjTWs0dldKeEZmZlF0RklIcnQyODBhIiwibmJmIjoxNzE4MTk0NTk5LCJhenAiOiJiU0dmUVFjTWs0dldKeEZmZlF0RklIcnQyODBhIiwic2NvcGUiOiJkZWZhdWx0IiwiaXNzIjoiaHR0cHM6XC9cL2xvY2FsaG9zdDo5NDQzXC9vYXV0aDJcL3Rva2VuIiwiZXhwIjo5MjIzMzcyMDM2ODU0Nzc1LCJpYXQiOjE3MTgxOTQ1OTksImp0aSI6IjExYzE0NDVkLTU0NjEtNDc2Yy05Y2U1LTM4YmFjOGJkZmQ2NSJ9.AO5ZU1gs5zHaHvyLCMZzpaTsQ-A49FsLdPEtktkxdPBePxgmTbfURlno0k-eJeQFkX9r4tXYfiI6_Ds6WqUuk4Nq5zHtiwjqn4XIZBIFmm8YkVIKag74-Xnuc1D4ZyQ7Oh2zHxhIdDIlzT9pif1-R7xYiLnrvyMaz-BobfNK4S_2tDKUFjFJ7ATfEdMZzbcJPTM8Tl0ud-og476zMQjYDTV4lgkZGfCnOLx8Zs83PQK-Z0QiRENzT8OlHWKIShEi7xAtSGMtWoP4k7BMNvFWK_GyWnipIFzstH8EoVav-5Iejm3bezshFFlFqWQpHjBE-YH8YaNFrAUPk_j7G9GIxg
  host-auto: https://gateway-stage-pdex.gov.cv/t/rni.gov/autoqueixa/1.0/v1/auto/queixa

  token-pdf: UE5NUzpQTkRFViNNUyMyMw==
  #token-pdf: UE5NUzpQTlBST0QjTVMjMjM=
  host-pdf: http://localhost:8088/sigo-pdf/
  #host-pdf: http://10.72.208.91:31382/sigo-pdf/
  #http://10.72.208.45:31437/sigo-pdf/generate/


  #notification:
  #  host: http://10.73.225.19:8080/SendingNotification/notification
  #  token: cG4ubm90aWZpY2F0aW9uLnNlcnZpY2U6WD50Qm5YcnNONVlMVmRkOA==



keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: <NOME_DO_REALM>
  resource: <NOME_DO_CLIENTE>
  public-client: true
  credentials:
    secret: <CLIENT_SECRET>
  ssl-required: external
  use-resource-role-mappings: true

notification:
  email:
    default-email-sender: pnotifica@policianacional.cv
    default-origin: PN_SIGO
  sms:
    default-origin: PN_SIGOIC
    ##default-source: Policia_Nac
    default-source: PN
